# Generated by Django 5.0.6 on 2026-09-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, choices=[('earth-explorer', 'Earth Explorer'), ('moon-explorer', 'Moon Explorer'), ('robot', 'Cosmic Robot'), ('mars-explorer', 'Mars Explorer'), ('saturn-explorer', 'Saturn Explorer'), ('nebula', 'Nebula Spirit'), ('ice-explorer', 'Ice Explorer'), ('void', 'Void Voyager')], default='', max_length=32),
        ),
    ]
