# Generated by Django 5.0.6 on 2026-09-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, choices=[('Nilo', 'The Wise Alien — Nilo'), ('Mobi', 'The Friendly Robot — Mobi'), ('Lumi', 'The Stargazer Spirit — Lumi'), ('Rico', 'The Comet Trickster — Rico'), ('Selu', 'The Moon Guardian — Selu'), ('Orbi', 'The Planet Keeper — Orbi'), ('Veya', 'The Cosmic Wanderer — Veya'), ('Soli', 'The Star Forger — Soli')], default='', max_length=32),
        ),
    ]
