export default {
  content: {
    relative: true,
    files: ["./index.html", "./src/**/*.{vue,ts}"],
  },
  theme: {
    extend: {
      colors: {
        "canvas": "rgb(var(--color-canvas) / <alpha-value>)",
        "surface": "rgb(var(--color-surface) / <alpha-value>)",
        "subtle": "rgb(var(--color-subtle) / <alpha-value>)",
        "muted": "rgb(var(--color-muted) / <alpha-value>)",
        "line": "rgb(var(--color-line) / <alpha-value>)",
        "line-soft": "rgb(var(--color-line-soft) / <alpha-value>)",
        "line-strong": "rgb(var(--color-line-strong) / <alpha-value>)",
        "heading": "rgb(var(--color-heading) / <alpha-value>)",
        "body": "rgb(var(--color-body) / <alpha-value>)",
        "copy": "rgb(var(--color-copy) / <alpha-value>)",
        "secondary": "rgb(var(--color-secondary) / <alpha-value>)",
        "quiet": "rgb(var(--color-quiet) / <alpha-value>)",
        "faint": "rgb(var(--color-faint) / <alpha-value>)",
        "accent": "rgb(var(--color-accent) / <alpha-value>)",
        "accent-strong": "rgb(var(--color-accent-strong) / <alpha-value>)",
        "primary": "rgb(var(--color-primary) / <alpha-value>)",
        "primary-hover": "rgb(var(--color-primary-hover) / <alpha-value>)",
        "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
        "on-primary-muted": "rgb(var(--color-on-primary-muted) / <alpha-value>)",
        "accent-soft": "rgb(var(--color-accent-soft) / <alpha-value>)",
        "accent-muted": "rgb(var(--color-accent-muted) / <alpha-value>)",
        "accent-line": "rgb(var(--color-accent-line) / <alpha-value>)",
        "accent-line-strong": "rgb(var(--color-accent-line-strong) / <alpha-value>)",
        "accent-glow": "rgb(var(--color-accent-glow) / <alpha-value>)",
        "warning-soft": "rgb(var(--color-warning-soft) / <alpha-value>)",
        "warning-muted": "rgb(var(--color-warning-muted) / <alpha-value>)",
        "warning-line": "rgb(var(--color-warning-line) / <alpha-value>)",
        "warning": "rgb(var(--color-warning) / <alpha-value>)",
        "warning-bright": "rgb(var(--color-warning-bright) / <alpha-value>)",
        "warning-ink": "rgb(var(--color-warning-ink) / <alpha-value>)",
        "warning-copy": "rgb(var(--color-warning-copy) / <alpha-value>)",
        "warning-icon": "rgb(var(--color-warning-icon) / <alpha-value>)",
        "chart-neutral": "rgb(var(--color-chart-neutral) / <alpha-value>)",
        "dot-neutral": "rgb(var(--color-dot-neutral) / <alpha-value>)",
        "badge-ink": "rgb(var(--color-badge-ink) / <alpha-value>)",
        "selection": "rgb(var(--color-selection) / <alpha-value>)",
      },
      fontFamily: {
        display: ["Fraunces", "ui-serif", "Georgia", "serif"],
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      borderRadius: {
        xl2: "1.25rem",
      },
      boxShadow: {
        soft: "0 1px 2px rgba(33, 30, 27, 0.04), 0 8px 24px -12px rgba(33, 30, 27, 0.10)",
      },
    },
  },
  plugins: [],
};
