# Generated by Django 5.0.6 on 2026-09-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, unique=True)),
                ('definition', models.TextField(blank=True)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('usage_notes', models.TextField(blank=True)),
                ('collocations', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Word',
                'verbose_name_plural': 'Global Words (Dictionary)',
                'ordering': ['word'],
            },
        ),
    ]
