# Generated by Django 5.0.6 on 2026-09-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_globalword'),
        ('words', '0002_word_pronunciation'),
    ]

    operations = [
    ]
