# Generated by Django 5.0.6 on 2026-09-07 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_pronunciation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='word',
            name='unique_word_per_user',
        ),
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('user', 'language', 'word'), name='unique_word_per_user_language'),
        ),
    ]
