# Generated by Django 5.0.6 on 2026-09-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_merge_0002_globalword_0002_word_pronunciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalword',
            name='pronunciation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
