# Generated by Django 5.0.6 on 2026-09-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_globalword_pronunciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_mastered',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
